// Builds src/themes/themes.css from the tokens: the file is a build artifact checked in, because the package has no
// build step. A test fails when it is stale; regenerate with `node packages/ui/scripts/build-css.mjs`.

import { font, motion, radius, space } from "../tokens.ts";
import { defaultTheme, type Theme, themes } from "./ids.ts";
import { brand, type ThemeTokens, themeTokens } from "./tokens.ts";

/** `bg2` -> `--bg-2`, `docInk2` -> `--doc-ink-2`, `accentInk` -> `--accent-ink` (the names of the prototype). */
export function cssVarName(role: string): string {
  return `--${role.replace(/[A-Z0-9]/g, (m) => `-${m.toLowerCase()}`)}`;
}

const seconds = (ms: number) => `${ms / 1000}s`;

function block(selector: string, decls: [string, string][]): string {
  return `${selector} {\n${decls.map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`;
}

function modeDecls(t: ThemeTokens): [string, string][] {
  return Object.entries(t)
    .filter(([role]) => role !== "themeColor")
    .map(([role, value]) => [cssVarName(role), value]);
}

function themeSelector(theme: Theme): string {
  const byAttribute = `[data-theme="${theme}"]`;
  return theme === defaultTheme ? `:root,\n${byAttribute}` : byAttribute;
}

export function buildThemesCss(): string {
  const core: [string, string][] = [
    ["--asphalt", brand.asphalt],
    ["--signal", brand.signal],
    ["--signal-dark", brand.signalDark],
    ["--paper", brand.paper],
    ["--display", font.display],
    ["--sans", font.sans],
    ["--cond", font.cond],
    ["--mono", font.mono],
    ["--gut", space.gut],
    ["--max", `${space.max}px`],
    ["--head", `${space.head}px`],
    ["--r1", `${radius.r1}px`],
    ["--r2", `${radius.r2}px`],
    ["--dur-1", seconds(motion.dur.fast)],
    ["--dur-2", seconds(motion.dur.base)],
    ["--dur-3", seconds(motion.dur.slow)],
    ["--ease-out", motion.ease.out],
    ["--ease-io", motion.ease.io],
    ["--ease-stamp", motion.ease.stamp],
  ];
  return [
    "/* Generated by packages/ui/scripts/build-css.mjs from src/themes/tokens.ts. Do not edit by hand. */\n",
    block(":root", core),
    "/* In IBM Plex Mono the sign U+02BB looks like an acute accent: Uzbek uses Noto Sans Mono. */",
    block('html[lang="uz-Latn"]', [["--mono", font.monoUz]]),
    "/* One rule per theme; the default theme also answers to :root, so a page without the attribute is night. */",
    ...themes.map((theme) => block(themeSelector(theme), modeDecls(themeTokens[theme]))),
  ].join("\n");
}
