// Renders the mark nivel-1 ("Отметка уровня", DECISIONS R-17) to two small PNGs and writes src/90_logo.js.
// Sheets cannot show SVG, so the panel uses PNG: dark for the paper theme, light for the night theme.
// Usage: node scripts/make-logo.mjs   (needs Playwright with Edge; the browser is hidden)
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(join(here, "..", "..", "..", "package.json"));
const { chromium } = require("@playwright/test");

const mark = (dark, orange) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="2 14 60 36" width="300" height="180"><path fill="${dark}" d="M8 16h52v8h-52Z"/><path fill="${orange}" d="M8 24L24 24L24 40Z"/><path fill="${dark}" d="M24 24L40 24L24 40Z"/><path fill="${dark}" d="M4 40h56v8h-56Z"/></svg>`;

const variants = { dark: mark("#1D1D1B", "#D9501A"), light: mark("#F1EFEA", "#F06A30") };

const profile = mkdtempSync(join(tmpdir(), "nivel-logo-"));
const context = await chromium.launchPersistentContext(profile, {
  headless: true,
  channel: "msedge",
  viewport: { width: 300, height: 180 },
});
try {
  const out = {};
  for (const [name, svg] of Object.entries(variants)) {
    const page = await context.newPage();
    await page.setContent(`<html><body style="margin:0;background:transparent">${svg}</body></html>`);
    const buf = await page.screenshot({ omitBackground: true, clip: { x: 0, y: 0, width: 300, height: 180 } });
    out[name] = buf.toString("base64");
    await page.close();
  }
  const text = `/**
 * Mark nivel-1 as PNG (generated by scripts/make-logo.mjs; do not edit by hand).
 * The panel shows it at 40 px height: dark for the paper theme, light for the night one.
 */
const NV_LOGO_PNG = {
  dark: "${out.dark}",
  light: "${out.light}",
};
`;
  writeFileSync(join(here, "..", "src", "90_logo.js"), text);
  console.log("logo written", out.dark.length, out.light.length);
} finally {
  await context.close();
  rmSync(profile, { recursive: true, force: true });
}
