// Russian captions of the catalog form (the admin is Russian only). Keys are the names of the contract
// (`@nivel/contracts/catalog`); a key that means a little different thing in two categories has one general caption.

export const CATALOG_LABELS: Record<string, string> = {
  // the position
  category: "Категория",
  brand: "Бренд",
  model: "Модель",
  mpn: "Артикул производителя (MPN)",
  color: "Цвет",
  lighting: "Подсветка",
  feeGroup: "Группа платы",
  returnable: "Можно вернуть магазину",
  manualOnly: "Только вручную (не в автосборке)",
  description: "Описание",
  "description.uz": "Описание (uz)",
  "description.ru": "Описание (ru)",
  spec: "Характеристики",
  status: "Статус",
  isDemo: "Демо",
  // shared
  socket: "Сокет",
  sockets: "Сокеты",
  chipset: "Чипсет",
  chipsets: "Совместимые чипсеты",
  formFactor: "Форм-фактор",
  heightMm: "Высота, мм",
  lengthMm: "Длина, мм",
  count: "Штук",
  vesa: "VESA",
  // cpu
  cores: "Ядра",
  threads: "Потоки",
  boostGhz: "Макс. частота, ГГц",
  tdpW: "TDP, Вт",
  maxPowerW: "Пиковая мощность, Вт",
  hasIgpu: "Встроенная графика",
  memTypes: "Типы памяти",
  memMaxMts: "Макс. скорость памяти, МТ/с",
  boxCooler: "Кулер в комплекте",
  minBiosByChipset: "Мин. версия BIOS по чипсету (JSON)",
  // motherboard
  ramType: "Тип памяти",
  ramSlots: "Слотов памяти",
  ramMaxGb: "Макс. объём памяти, ГБ",
  ramMaxMts: "Макс. скорость памяти, МТ/с",
  m2: "Слоты M.2",
  "m2.id": "Обозначение",
  "m2.pcieGen": "Поколение PCIe",
  "m2.maxLenMm": "Макс. длина, мм",
  "m2.disablesSata": "Отключает порты SATA",
  sataPorts: "Порты SATA",
  pcieX16Slots: "Слоты PCIe x16",
  fanHeaders: "Разъёмы вентиляторов",
  argb5vHeaders: "Разъёмы ARGB 5 В",
  rgb12vHeaders: "Разъёмы RGB 12 В",
  wifi: "Wi-Fi",
  bluetooth: "Bluetooth",
  biosFlashback: "BIOS Flashback",
  shippedBios: "Версия BIOS с завода",
  // memory
  type: "Тип",
  kitGb: "Объём комплекта, ГБ",
  modules: "Модулей",
  mts: "Скорость, МТ/с",
  cl: "Задержка CL",
  profile: "Профиль",
  // ssd
  iface: "Интерфейс",
  capacityGb: "Объём, ГБ",
  pcieGen: "Поколение PCIe",
  tbw: "Ресурс TBW, ТБ",
  heatsinkHeightMm: "Высота радиатора, мм",
  // gpu
  chip: "Чип",
  vramGb: "Видеопамять, ГБ",
  slots: "Занимает слотов",
  power: "Разъёмы питания",
  "power.conn": "Разъём",
  "power.count": "Штук",
  adapterInBox: "Переходник в комплекте",
  tgpW: "TGP, Вт",
  vendorRecommendedPsuW: "БП по рекомендации производителя, Вт",
  hwEncoders: "Аппаратные кодеки (по одному в строке)",
  // psu
  watts: "Мощность, Вт",
  rating: "Сертификат 80 Plus",
  modular: "Модульность",
  pcie8pin: "Разъёмов PCIe 8 pin",
  native12v2x6: "Разъёмов 12V-2x6",
  atx3: "ATX 3.x",
  // case
  boards: "Платы",
  gpuMaxLenMm: "Макс. длина видеокарты, мм",
  gpuMaxLenWithFrontRadMm: "…с фронтальным радиатором, мм",
  coolerMaxHeightMm: "Макс. высота кулера, мм",
  radiators: "Места под радиаторы",
  "radiators.side": "Сторона",
  "radiators.sizesMm": "Размеры, мм",
  "radiators.maxThicknessMm": "Макс. толщина, мм",
  psuFF: "Форм-факторы БП",
  psuMaxLenMm: "Макс. длина БП, мм",
  expansionSlots: "Слотов расширения",
  fanMounts: "Мест под вентиляторы",
  fansIncluded: "Вентиляторов в комплекте",
  dimsMm: "Габариты, мм",
  w: "Ширина",
  d: "Глубина",
  h: "Высота",
  // coolers, fans
  ramClearanceMm: "Запас над памятью, мм",
  tdpRatedW: "Рассеиваемая мощность, Вт",
  radMm: "Размер радиатора, мм",
  radThicknessWithFansMm: "Толщина радиатора с вентиляторами, мм",
  tubeLenMm: "Длина шлангов, мм",
  pumpW: "Мощность помпы, Вт",
  sizeMm: "Размер, мм",
  conn: "Разъём",
  argb: "ARGB",
  // monitor
  diagIn: "Диагональ, дюймы",
  aspect: "Соотношение сторон",
  resolution: "Разрешение (1920x1080)",
  hz: "Частота, Гц",
  panelWmm: "Ширина панели, мм",
  panelHmm: "Высота панели, мм",
  depthWithStandMm: "Глубина с подставкой, мм",
  standFootprintMm: "Основание подставки, мм",
  weightNoStandKg: "Вес без подставки, кг",
  curved: "Изогнутый",
  // arm, desk, chair
  reachMinMm: "Вылет от, мм",
  reachMaxMm: "Вылет до, мм",
  poleHeightMm: "Высота стойки, мм",
  mount: "Крепление",
  topThicknessMinMm: "Толщина столешницы от, мм",
  topThicknessMaxMm: "Толщина столешницы до, мм",
  loadMinKg: "Нагрузка от, кг",
  loadMaxKg: "Нагрузка до, кг",
  diagMinIn: "Диагональ от, дюймы",
  diagMaxIn: "Диагональ до, дюймы",
  screens: "Экранов",
  topWmm: "Ширина столешницы, мм",
  topDmm: "Глубина столешницы, мм",
  heightMinMm: "Высота от, мм",
  heightMaxMm: "Высота до, мм",
  topThicknessMm: "Толщина столешницы, мм",
  legZonesMm: "Зоны ног",
  "legZonesMm.fromMm": "От, мм",
  "legZonesMm.toMm": "До, мм",
  cableCutout: "Вырез под кабели",
  loadKg: "Нагрузка, кг",
  motors: "Моторов",
  baseDiamMm: "Диаметр основания, мм",
  seatHeightMinMm: "Высота сиденья от, мм",
  seatHeightMaxMm: "Высота сиденья до, мм",
  rollbackZoneMm: "Зона отката, мм",
  userHeightCm: "Рост пользователя, см",
  "userHeightCm.0": "от",
  "userHeightCm.1": "до",
  userMaxKg: "Макс. вес пользователя, кг",
};

/** Words for the values of enumerations that have a Russian word; the rest (AM5, DDR5, ATX) show as they are. */
export const OPTION_LABELS: Record<string, Record<string, string>> = {
  color: { black: "Чёрный", white: "Белый", gray: "Серый", other: "Другой" },
  lighting: { none: "Нет", rgb: "RGB", argb: "ARGB" },
  feeGroup: { pc: "ПК", mount: "Монтаж", outside_scale: "Вне шкалы" },
  profile: { none: "Нет", both: "XMP и EXPO" },
  rating: { none: "Нет" },
  modular: { no: "Нет", semi: "Частично", full: "Полностью" },
  mount: { clamp: "Струбцина", grommet: "Через отверстие", both: "Оба способа" },
  side: { front: "Спереди", top: "Сверху", rear: "Сзади", side: "Сбоку", bottom: "Снизу" },
};

/** Groups of characteristics shown as sections of the form (the keys of `spec`); the rest go to "Прочее". */
export const SPEC_GROUPS: Record<string, { title: string; keys: string[] }[]> = {
  cpu: [
    { title: "Основное", keys: ["socket", "cores", "threads", "boostGhz", "hasIgpu", "boxCooler"] },
    { title: "Питание", keys: ["tdpW", "maxPowerW"] },
    { title: "Память и платы", keys: ["memTypes", "memMaxMts", "chipsets", "minBiosByChipset"] },
  ],
  mb: [
    { title: "Основное", keys: ["socket", "chipset", "formFactor", "shippedBios", "biosFlashback"] },
    { title: "Память", keys: ["ramType", "ramSlots", "ramMaxGb", "ramMaxMts"] },
    { title: "Накопители и слоты", keys: ["m2", "sataPorts", "pcieX16Slots"] },
    { title: "Разъёмы и связь", keys: ["fanHeaders", "argb5vHeaders", "rgb12vHeaders", "wifi", "bluetooth"] },
  ],
  ram: [{ title: "Основное", keys: ["type", "kitGb", "modules", "mts", "cl", "profile", "heightMm", "lighting"] }],
  ssd: [
    { title: "Основное", keys: ["iface", "formFactor", "capacityGb", "pcieGen"] },
    { title: "Ресурс и размеры", keys: ["tbw", "heatsinkHeightMm"] },
  ],
  gpu: [
    { title: "Чип и память", keys: ["chip", "vramGb", "hwEncoders"] },
    { title: "Размеры", keys: ["lengthMm", "heightMm", "slots"] },
    { title: "Питание", keys: ["power", "adapterInBox", "tgpW", "vendorRecommendedPsuW"] },
  ],
  psu: [
    { title: "Основное", keys: ["watts", "rating", "formFactor", "lengthMm", "modular", "atx3"] },
    { title: "Разъёмы", keys: ["pcie8pin", "native12v2x6"] },
  ],
  case: [
    { title: "Платы и блок питания", keys: ["boards", "psuFF", "psuMaxLenMm", "expansionSlots"] },
    { title: "Видеокарта и кулер", keys: ["gpuMaxLenMm", "gpuMaxLenWithFrontRadMm", "coolerMaxHeightMm"] },
    { title: "Охлаждение", keys: ["radiators", "fanMounts", "fansIncluded"] },
    { title: "Габариты", keys: ["dimsMm"] },
  ],
};
