// Creates .env.local with random development secrets.
// Usage: node tools/init-env.mjs [--slot N] [--from <path to another .env.local>] [--force]
// --from copies database passwords and keys (a worktree shares the dev and test clusters with the main folder).
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { parseEnvFile, portBase, ROOT } from "./lib/env.mjs";

const { values: args } = parseArgs({
  options: {
    slot: { type: "string", default: "0" },
    from: { type: "string" },
    force: { type: "boolean", default: false },
  },
});

const target = join(ROOT, ".env.local");
if (existsSync(target) && !args.force) {
  console.error(".env.local already exists; pass --force to overwrite");
  process.exit(1);
}

const slot = Number.parseInt(args.slot, 10);
if (!Number.isInteger(slot) || slot < 0 || slot > 9) {
  console.error("--slot must be 0..9");
  process.exit(1);
}

const source = args.from ? parseEnvFile(args.from) : {};
const hex = (n) => randomBytes(n).toString("hex");
const b64 = (n) => randomBytes(n).toString("base64");
const keep = (key, make) => source[key] || make();

const pw = {
  POSTGRES_PASSWORD: keep("POSTGRES_PASSWORD", () => hex(18)),
  NIVEL_MIGRATOR_PASSWORD: keep("NIVEL_MIGRATOR_PASSWORD", () => hex(18)),
  NIVEL_WEB_PASSWORD: keep("NIVEL_WEB_PASSWORD", () => hex(18)),
  NIVEL_ADMIN_PASSWORD: keep("NIVEL_ADMIN_PASSWORD", () => hex(18)),
  NIVEL_BOT_PASSWORD: keep("NIVEL_BOT_PASSWORD", () => hex(18)),
  NIVEL_WORKER_PASSWORD: keep("NIVEL_WORKER_PASSWORD", () => hex(18)),
  NIVEL_UMAMI_PASSWORD: keep("NIVEL_UMAMI_PASSWORD", () => hex(18)),
};

const dev = (role, password) => `postgres://${role}:${password}@127.0.0.1:54329/nivel`;
const test = (role, password) => `postgres://${role}:${password}@127.0.0.1:54339/nivel_s${slot}_test`;
const base = portBase(slot);

const values = {
  APP_MODE: "development",
  NIVEL_SLOT: String(slot),
  DATABASE_URL_WEB: dev("nivel_web", pw.NIVEL_WEB_PASSWORD),
  DATABASE_URL_ADMIN: dev("nivel_admin", pw.NIVEL_ADMIN_PASSWORD),
  DATABASE_URL_BOT: dev("nivel_bot", pw.NIVEL_BOT_PASSWORD),
  DATABASE_URL_WORKER: dev("nivel_worker", pw.NIVEL_WORKER_PASSWORD),
  DATABASE_URL_MIGRATOR: dev("nivel_migrator", pw.NIVEL_MIGRATOR_PASSWORD),
  TEST_DATABASE_URL_SUPER: `postgres://postgres:${pw.POSTGRES_PASSWORD}@127.0.0.1:54339/postgres`,
  TEST_DATABASE_URL_MIGRATOR: test("nivel_migrator", pw.NIVEL_MIGRATOR_PASSWORD),
  TEST_DATABASE_URL_WEB: test("nivel_web", pw.NIVEL_WEB_PASSWORD),
  TEST_DATABASE_URL_ADMIN: test("nivel_admin", pw.NIVEL_ADMIN_PASSWORD),
  TEST_DATABASE_URL_BOT: test("nivel_bot", pw.NIVEL_BOT_PASSWORD),
  TEST_DATABASE_URL_WORKER: test("nivel_worker", pw.NIVEL_WORKER_PASSWORD),
  ...pw,
  UMAMI_APP_SECRET: keep("UMAMI_APP_SECRET", () => hex(32)),
  BOT_TOKEN: source.BOT_TOKEN ?? "",
  BOT_MODE: "polling",
  BOT_WEBHOOK_SECRET: keep("BOT_WEBHOOK_SECRET", () => hex(24)),
  TELEGRAM_OWNER_IDS: source.TELEGRAM_OWNER_IDS ?? "",
  ANTHROPIC_API_KEY: source.ANTHROPIC_API_KEY ?? "",
  AI_ENABLED: "false",
  DATA_ENC_KEY: keep("DATA_ENC_KEY", () => b64(32)),
  REVALIDATE_HMAC_KEY: keep("REVALIDATE_HMAC_KEY", () => b64(32)),
  TMA_TOKEN_KEY: keep("TMA_TOKEN_KEY", () => b64(32)),
  PUBLIC_BASE_URL: `http://localhost:${base}`,
  ADMIN_BASE_URL: `http://localhost:${base + 1}`,
  FILES_DIR: ".data/files",
  MEDIA_DIR: ".data/media",
};

// Keep the order and comments of .env.example; append unknown keys at the end.
const example = readFileSync(join(ROOT, ".env.example"), "utf8").split(/\r?\n/);
const seen = new Set();
const lines = example.map((line) => {
  const m = /^([A-Z0-9_]+)=/.exec(line);
  if (!m) return line;
  seen.add(m[1]);
  return `${m[1]}=${values[m[1]] ?? ""}`;
});
for (const [k, v] of Object.entries(values)) if (!seen.has(k)) lines.push(`${k}=${v}`);
lines[0] = "# Generated by tools/init-env.mjs. Development secrets only; never commit.";
writeFileSync(target, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
console.log(`.env.local written for slot ${slot} (ports ${base}..${base + 3})`);
