// A card of an order built by hand for the tests that draw the blocks of the screen (not part of the application).
import type { OrderStatus } from "@nivel/domain/order";
import type { OrderCard, PaymentView, PurchaseView, QuoteView } from "../read-orders.ts";

const ID = (n: number) => `0199aaaa-bbbb-7ccc-8ddd-${String(n).padStart(12, "0")}`;
const AT = new Date("2026-10-12T05:00:00Z");

export const quoteOf = (over: Partial<QuoteView> = {}): QuoteView => ({
  id: ID(900),
  version: 2,
  status: "draft",
  validUntil: null,
  sentAt: null,
  manuallyCheckedAt: null,
  watermarkDraft: false,
  settingsVersion: "2026-10-05",
  compatVerdict: "ok",
  shelfLifeHours: 24,
  pdf: { uz: null, ru: null },
  totals: {
    componentsSum: 11_850_000,
    outsideScaleSum: 0,
    reserveBp: 300,
    reserveSum: 360_000,
    purchaseLimit: 12_210_000,
    feeTotal: 1_777_500,
    feeCommissionLine: 888_750,
    feeWorksLine: 888_750,
    advance: 533_250,
    final: 1_244_250,
    grandTotal: 13_987_500,
    effectiveRateBp: 1500,
    eligibility: "full_cycle",
    minEstimate: null,
    warnings: [],
  },
  lines: [
    {
      id: ID(901),
      productId: ID(801),
      title: "Ryzen 5 7600",
      categoryCode: "cpu",
      feeGroup: "pc",
      qty: 1,
      unitSum: 2_800_000,
      priceDate: "2026-10-12",
      confidence: "high",
      returnable: "yes",
      customerOwned: false,
      purchasedByIp: true,
    },
    {
      id: ID(902),
      productId: null,
      title: "Сборка и тест",
      categoryCode: "cable_mgmt",
      feeGroup: "mount",
      qty: 1,
      unitSum: 300_000,
      priceDate: null,
      confidence: null,
      returnable: "unknown",
      customerOwned: false,
      purchasedByIp: false,
    },
  ],
  ...over,
});

export const paymentOf = (over: Partial<PaymentView> = {}): PaymentView => ({
  id: ID(500),
  kind: "fee_advance",
  direction: "in",
  method: "xolis_qr",
  amountSum: 533_250,
  status: "expected",
  fiscalReceiptNo: null,
  bankDocNo: null,
  payerIsCustomer: true,
  thirdPartyStatementFileId: null,
  confirmedAt: null,
  confirmedBy: null,
  reversalOf: null,
  createdAt: AT,
  ...over,
});

export const purchaseOf = (over: Partial<PurchaseView> = {}): PurchaseView => ({
  id: ID(600),
  vendorName: "Test shop",
  quoteLineId: ID(901),
  qty: 1,
  amountSum: 2_800_000,
  discountSum: 0,
  refundOf: null,
  paidVia: "bank_transfer",
  receiptKind: "fiscal",
  receiptNo: "CH-1",
  esfNo: null,
  esfStatus: null,
  esfDue: null,
  serials: ["SN1"],
  vendorWarrantyUntil: "2029-10-12",
  boughtAt: AT,
  boughtBy: "owner-12345678",
  files: [{ id: ID(700), kind: "receipt" }],
  ...over,
});

export function cardOf(status: OrderStatus, over: Partial<OrderCard> = {}): OrderCard {
  return {
    order: {
      id: ID(1),
      number: "NV-2026-0001",
      leadId: ID(2),
      customerId: ID(3),
      contractScheme: "commission",
      kind: "pc",
      slot: "regular",
      complexBuild: false,
      status,
      feePrepaid: false,
      fundsReceived: false,
      fundsReceivedAt: null,
      purchaseNotBefore: null,
      firstOrderMeetingDone: false,
      currentQuoteId: ID(900),
      offerVersionUzId: null,
      offerVersionRuId: null,
      acceptedAt: null,
      reportDueAt: null,
      objectionUntil: null,
      refundDueAt: null,
      handedOverAt: null,
      warrantyUntil: null,
      cancel: null,
      documentedLossesSum: 0,
      podborCreditUntil: null,
      tgTopicId: null,
      assignee: null,
      createdAt: AT,
      updatedAt: AT,
    } as OrderCard["order"],
    customer: {
      id: ID(3),
      displayName: "Азиз Каримов",
      telegramUsername: "aziz_k",
      phone: null,
      district: "Юнусабад",
      lang: "ru",
      erased: false,
    },
    leadNumber: "L-2026-0001",
    offer: { uz: "published", ru: "published" },
    quote: quoteOf(),
    quoteVersions: [{ id: ID(900), version: 2, status: "draft", createdAt: AT }],
    events: [],
    payments: [],
    purchases: [],
    money: { fundsReceived: 0, receiptsTotal: 0, refunded: 0, documentedLosses: 0, hasLimitOverrunConsent: false },
    reports: [],
    acts: [],
    passport: null,
    warranty: [],
    consents: [],
    files: {},
    ...over,
  };
}

export { ID };
