/**
 * The "Настройки" sheet as data: every value is a named cell NV_*. Copy of DEFAULT_FEE_SETTINGS (2026-10-05) and of the
 * rules of threshold, reserves and reminders. No secrets here: tokens and keys live in Script Properties.
 *
 * type: bp (0..10 000), sum (>= 0), int, days, hours, text, bool, date, time, formula
 */
const NV_SETTINGS = [
  { group: "Плата" },
  {
    key: "pcLowBp",
    name: "NV_PC_LOW_BP",
    label: "Ставка платы ПК до порога",
    value: 1500,
    unit: "бп",
    source: "Р-8",
    type: "bp",
  },
  {
    key: "pcHighBp",
    name: "NV_PC_HIGH_BP",
    label: "Ставка платы ПК от порога",
    value: 1000,
    unit: "бп",
    source: "Р-8",
    type: "bp",
  },
  {
    key: "pcThreshold",
    name: "NV_PC_THRESHOLD",
    label: "Порог шкалы ПК",
    value: 20000000,
    unit: "сум",
    source: "Р-8",
    type: "sum",
  },
  {
    key: "pcHighMinFee",
    name: "NV_PC_HIGH_MIN_FEE",
    label: "Минимум платы от порога",
    value: 3000000,
    unit: "сум",
    source: "Р-8",
    type: "sum",
  },
  {
    key: "mountBp",
    name: "NV_MOUNT_BP",
    label: "Ставка платы за монтаж",
    value: 1500,
    unit: "бп",
    source: "Р-8",
    type: "bp",
  },
  {
    key: "complexBp",
    name: "NV_COMPLEX_BP",
    label: "Ставка сложной сборки",
    value: 1500,
    unit: "бп",
    source: "Р-8",
    type: "bp",
  },
  {
    key: "minPc",
    name: "NV_MIN_PC",
    label: "Минимум базы ПК, полный цикл",
    value: 6700000,
    unit: "сум",
    source: "Р-8",
    type: "sum",
  },
  {
    key: "minWindow",
    name: "NV_MIN_WINDOW",
    label: "Минимум базы ПК, свободное окно",
    value: 4500000,
    unit: "сум",
    source: "Р-8",
    type: "sum",
  },
  {
    key: "minSetup",
    name: "NV_MIN_SETUP",
    label: "Минимум базы сетапа, полный цикл",
    value: 13300000,
    unit: "сум",
    source: "Р-8",
    type: "sum",
  },
  {
    key: "minUpgrade",
    name: "NV_MIN_UPGRADE",
    label: "Минимум сметы апгрейда (новый заказ по той же шкале)",
    value: 4000000,
    unit: "сум",
    source: "Р-26",
    type: "sum",
  },
  {
    key: "stageSelectionBp",
    name: "NV_STAGE_SELECTION_BP",
    label: "Доля этапа: подбор",
    value: 2000,
    unit: "бп",
    source: "4.7",
    type: "bp",
    stage: true,
  },
  {
    key: "stagePurchaseBp",
    name: "NV_STAGE_PURCHASE_BP",
    label: "Доля этапа: закупка",
    value: 3000,
    unit: "бп",
    source: "4.7",
    type: "bp",
    stage: true,
  },
  {
    key: "stageAssemblyBp",
    name: "NV_STAGE_ASSEMBLY_BP",
    label: "Доля этапа: сборка и тест",
    value: 3500,
    unit: "бп",
    source: "4.7",
    type: "bp",
    stage: true,
  },
  {
    key: "stageHandoverBp",
    name: "NV_STAGE_HANDOVER_BP",
    label: "Доля этапа: сдача",
    value: 1500,
    unit: "бп",
    source: "4.7",
    type: "bp",
    stage: true,
  },
  {
    key: "commissionBp",
    name: "NV_COMMISSION_BP",
    label: "Доля строки «вознаграждение» (подбор + закупка)",
    value: 5000,
    unit: "бп",
    source: "4.6",
    type: "formula",
    formula: "=NV_STAGE_SELECTION_BP+NV_STAGE_PURCHASE_BP",
  },
  { key: "advanceBp", name: "NV_ADVANCE_BP", label: "Аванс платы", value: 3000, unit: "бп", source: "Р-9", type: "bp" },
  {
    key: "podborBp",
    name: "NV_PODBOR_BP",
    label: "«Подбор»: доля платы по шкале",
    value: 2000,
    unit: "бп",
    source: "Р-26",
    type: "bp",
  },
  {
    key: "podborCreditDays",
    name: "NV_PODBOR_CREDIT_DAYS",
    label: "«Подбор» засчитывается при заказе в течение",
    value: 30,
    unit: "дн.",
    source: "Р-26",
    type: "int",
  },
  {
    key: "afterTestsBp",
    name: "NV_AFTER_TESTS_RETAIN_BP",
    label: "Заработано после тестов",
    value: 8500,
    unit: "бп",
    source: "4.7",
    type: "bp",
  },

  { group: "Смета и деньги на закупку" },
  {
    key: "reserveBp",
    name: "NV_RESERVE_BP",
    label: "Резерв на рост цен",
    value: 300,
    unit: "бп",
    source: "Р-10",
    type: "bp",
  },
  {
    key: "reserveHighBp",
    name: "NV_RESERVE_HIGH_BP",
    label: "Резерв при большой доле памяти и SSD",
    value: 500,
    unit: "бп",
    source: "Р-10",
    type: "bp",
  },
  {
    key: "reserveHighShareBp",
    name: "NV_RESERVE_HIGH_SHARE_BP",
    label: "Доля памяти и SSD для повышенного резерва",
    value: 2500,
    unit: "бп",
    source: "Р-10",
    type: "bp",
  },
  {
    key: "reserveStep",
    name: "NV_RESERVE_STEP",
    label: "Шаг округления резерва вверх",
    value: 10000,
    unit: "сум",
    source: "Р-10",
    type: "sum",
  },
  {
    key: "shelfHours",
    name: "NV_SHELF_HOURS",
    label: "Срок действия сметы",
    value: 24,
    unit: "ч",
    source: "4.9",
    type: "int",
  },
  {
    key: "shelfHoursFurniture",
    name: "NV_SHELF_HOURS_FURNITURE",
    label: "Срок сметы: только мебель и декор",
    value: 72,
    unit: "ч",
    source: "4.9",
    type: "int",
  },
  {
    key: "meetingFrom",
    name: "NV_MEETING_FROM",
    label: "Встреча при первом заказе от",
    value: 15000000,
    unit: "сум",
    source: "4.9",
    type: "sum",
  },
  {
    key: "maxBudget",
    name: "NV_MAX_BUDGET",
    label: "Предел бюджета в калькуляторе",
    value: 1000000000000,
    unit: "сум",
    source: "MAX_BUDGET_SUM",
    type: "sum",
  },

  { group: "Сроки" },
  {
    key: "reportTargetHours",
    name: "NV_REPORT_TARGET_H",
    label: "Отчёт о закупке: цель",
    value: 24,
    unit: "ч",
    source: "4.9",
    type: "int",
  },
  {
    key: "reportDeadlineHours",
    name: "NV_REPORT_DEADLINE_H",
    label: "Отчёт о закупке: крайний срок",
    value: 48,
    unit: "ч",
    source: "4.9",
    type: "int",
  },
  {
    key: "objectionDays",
    name: "NV_OBJECTION_DAYS",
    label: "Срок возражений",
    value: 3,
    unit: "р. д.",
    source: "4.9",
    type: "int",
  },
  {
    key: "refundDays",
    name: "NV_REFUND_DAYS",
    label: "Срок возврата остатка и отмены",
    value: 5,
    unit: "р. д.",
    source: "4.9",
    type: "int",
  },
  {
    key: "esfDays",
    name: "NV_ESF_DAYS",
    label: "Срок подписания ЭСФ",
    value: 10,
    unit: "дн.",
    source: "Р-7",
    type: "int",
  },
  {
    key: "warrantyMonths",
    name: "NV_WARRANTY_MONTHS",
    label: "Гарантия на весь сетап",
    value: 12,
    unit: "мес.",
    source: "Р-12",
    type: "int",
  },
  {
    key: "aftercareShort",
    name: "NV_AFTERCARE_SHORT",
    label: "Сопровождение после сдачи, 1",
    value: 7,
    unit: "дн.",
    source: "4.9",
    type: "int",
  },
  {
    key: "aftercareLong",
    name: "NV_AFTERCARE_LONG",
    label: "Сопровождение после сдачи, 2",
    value: 30,
    unit: "дн.",
    source: "4.9",
    type: "int",
  },
  {
    key: "firstResponseHours",
    name: "NV_FIRST_RESPONSE_HOURS",
    label: "Первый ответ на заявку",
    value: 2,
    unit: "ч",
    source: "MARKETING 8.1",
    type: "int",
  },
  {
    key: "responseFrom",
    name: "NV_RESPONSE_FROM",
    label: "Часы ответа: с",
    value: "10:00",
    unit: "ч:мин",
    source: "MARKETING 8.1",
    type: "time",
  },
  {
    key: "responseTo",
    name: "NV_RESPONSE_TO",
    label: "Часы ответа: до (пн–сб)",
    value: "19:00",
    unit: "ч:мин",
    source: "MARKETING 8.1",
    type: "time",
  },
  {
    key: "cycleTargetDays",
    name: "NV_CYCLE_TARGET_DAYS",
    label: "Цель цикла «принят → сдан»",
    value: 10,
    unit: "дн.",
    source: "решение владельца",
    type: "int",
  },
  {
    key: "worsePct",
    name: "NV_WORSE_PCT",
    label: "Плитка «хуже»: изменение к прошлому периоду не меньше",
    value: 20,
    unit: "%",
    source: "решение владельца",
    type: "int",
  },
  {
    key: "cacLimit",
    name: "NV_CAC_LIMIT",
    label: "Предел цены клиента в канале",
    value: 500000,
    unit: "сум",
    source: "MARKETING 3.3",
    type: "sum",
  },

  { group: "Порог оборота" },
  {
    key: "annualLimit",
    name: "NV_ANNUAL_LIMIT",
    label: "Годовой порог сделок",
    value: 1000000000,
    unit: "сум",
    source: "НК ст. 461",
    type: "sum",
  },
  {
    key: "regDate",
    name: "NV_REG_DATE",
    label: "Дата регистрации ЯТТ (пусто до регистрации)",
    value: "",
    unit: "дата",
    source: "открытый вопрос",
    type: "date",
  },
  {
    key: "proportion",
    name: "NV_PROPORTION",
    label: "Пропорция в год регистрации",
    value: "Без дня регистрации",
    unit: "",
    source: "4.8",
    type: "text",
    list: ["Без дня регистрации", "С днём регистрации"],
  },
  {
    key: "alert1",
    name: "NV_ALERT_1",
    label: "Рубеж оповещения 1",
    value: 6000,
    unit: "бп",
    source: "4.8",
    type: "bp",
    alert: true,
  },
  {
    key: "alert2",
    name: "NV_ALERT_2",
    label: "Рубеж оповещения 2 (бухгалтер уровня 2)",
    value: 7000,
    unit: "бп",
    source: "4.8",
    type: "bp",
    alert: true,
  },
  {
    key: "alert3",
    name: "NV_ALERT_3",
    label: "Рубеж оповещения 3",
    value: 8000,
    unit: "бп",
    source: "4.8",
    type: "bp",
    alert: true,
  },
  {
    key: "alert4",
    name: "NV_ALERT_4",
    label: "Рубеж оповещения 4",
    value: 9000,
    unit: "бп",
    source: "4.8",
    type: "bp",
    alert: true,
  },
  {
    key: "alert5",
    name: "NV_ALERT_5",
    label: "Рубеж оповещения 5",
    value: 10000,
    unit: "бп",
    source: "4.8",
    type: "bp",
    alert: true,
  },
  {
    key: "alertAckPct",
    name: "NV_ALERT_ACK_PCT",
    label: "Рубеж порога прочитан (до какого %; 0 — нет)",
    value: 0,
    unit: "%",
    source: "решение владельца",
    type: "int",
  },
  {
    key: "planCap2026",
    name: "NV_PLAN_CAP_2026",
    label: "План 2026 года: сделки не больше",
    value: 200000000,
    unit: "сум",
    source: "Р-7",
    type: "sum",
  },

  { group: "Налоги и резервы" },
  {
    key: "turnoverTaxBp",
    name: "NV_TURNOVER_TAX_BP",
    label: "Налог с оборота с платы",
    value: 100,
    unit: "бп",
    source: "Р-7",
    type: "bp",
  },
  {
    key: "socialTax",
    name: "NV_SOCIAL_TAX",
    label: "Социальный налог, в месяц (до 15 числа)",
    value: 440000,
    unit: "сум",
    source: "Р-7",
    type: "sum",
  },
  {
    key: "warrantyRateBp",
    name: "NV_WARRANTY_RATE_BP",
    label: "Резерв гарантии: ставка взноса",
    value: 200,
    unit: "бп",
    source: "Р-12",
    type: "bp",
  },
  {
    key: "warrantyMin",
    name: "NV_WARRANTY_MIN",
    label: "Резерв гарантии: минимум взноса",
    value: 150000,
    unit: "сум",
    source: "Р-12",
    type: "sum",
  },
  {
    key: "warrantyMatureBp",
    name: "NV_WARRANTY_MATURE_BP",
    label: "Резерв гарантии: ставка зрелого фонда",
    value: 100,
    unit: "бп",
    source: "Р-12",
    type: "bp",
  },
  {
    key: "warrantyMatureBalance",
    name: "NV_WARRANTY_MATURE_BALANCE",
    label: "Фонд зрелый: баланс от",
    value: 10000000,
    unit: "сум",
    source: "Р-12",
    type: "sum",
  },
  {
    key: "warrantyMatureOrders",
    name: "NV_WARRANTY_MATURE_ORDERS",
    label: "Фонд зрелый: закрыто заказов от",
    value: 30,
    unit: "шт.",
    source: "Р-12",
    type: "int",
  },
  {
    key: "warrantyMatureLossBp",
    name: "NV_WARRANTY_MATURE_LOSS_BP",
    label: "Фонд зрелый: потери за 12 мес. меньше",
    value: 50,
    unit: "бп",
    source: "Р-12",
    type: "bp",
  },
  {
    key: "warrantyStart",
    name: "NV_WARRANTY_START",
    label: "Стартовый взнос в гарантийный резерв",
    value: 3000000,
    unit: "сум",
    source: "Р-12",
    type: "sum",
  },
  {
    key: "xolisWithholds",
    name: "NV_XOLIS_WITHHOLDS",
    label: "Xolis удерживает налог 1 % сам (свой расчёт не нужен)",
    value: true,
    unit: "",
    source: "Р-10, Р-7: открытый вопрос",
    type: "bool",
  },
  {
    key: "xolisWithdrawBp",
    name: "NV_XOLIS_WITHDRAW_BP",
    label: "Комиссия Xolis за вывод платы на счёт",
    value: 100,
    unit: "бп",
    source: "Р-10",
    type: "bp",
  },
  {
    key: "taxRiskBp",
    name: "NV_TAX_RISK_BP",
    label: "Налоговый резерв: доля чеков",
    value: 100,
    unit: "бп",
    source: "Р-7",
    type: "bp",
  },
  {
    key: "taxRiskActive",
    name: "NV_TAX_RISK_ACTIVE",
    label: "Налоговый резерв действует (до ответа налоговой)",
    value: true,
    unit: "",
    source: "Р-7",
    type: "bool",
  },

  { group: "Сводка и напоминания" },
  {
    key: "digestTime",
    name: "NV_DIGEST_TIME",
    label: "Время ежедневной сводки",
    value: "09:00",
    unit: "ч:мин",
    source: "решение владельца",
    type: "time",
  },
  {
    key: "digestSunday",
    name: "NV_DIGEST_SUNDAY",
    label: "Сводка по воскресеньям",
    value: false,
    unit: "",
    source: "открытый вопрос",
    type: "bool",
  },
  {
    key: "digestChannel",
    name: "NV_DIGEST_CHANNEL",
    label: "Канал сводки",
    value: "Telegram",
    unit: "",
    source: "решение владельца",
    type: "text",
    list: ["Telegram", "Почта"],
  },

  { group: "Интеграция с платформой" },
  {
    key: "webhookOn",
    name: "NV_WEBHOOK_ON",
    label: "Интеграция включена",
    value: false,
    unit: "",
    source: "WP-14",
    type: "bool",
  },
  {
    key: "webhookEnv",
    name: "NV_WEBHOOK_ENV",
    label: "Принимать среду",
    value: "production",
    unit: "",
    source: "WP-14",
    type: "text",
    list: ["production", "staging", "development"],
  },
  {
    key: "hmacSkewSec",
    name: "NV_HMAC_SKEW_SEC",
    label: "Допуск часов отправителя",
    value: 300,
    unit: "с",
    source: "WP-14",
    type: "int",
  },

  { group: "Служебное" },
  {
    key: "tz",
    name: "NV_TZ",
    label: "Часовой пояс",
    value: "Asia/Tashkent",
    unit: "",
    source: "",
    type: "text",
    readonly: true,
  },
  {
    key: "locale",
    name: "NV_LOCALE",
    label: "Локаль",
    value: "ru_RU",
    unit: "",
    source: "",
    type: "text",
    readonly: true,
  },
  {
    key: "schema",
    name: "NV_SCHEMA",
    label: "Версия схемы CRM",
    value: String(NV_SCHEMA_VERSION),
    unit: "",
    source: "",
    type: "text",
    readonly: true,
  },
  {
    key: "feeVersion",
    name: "NV_FEE_VERSION",
    label: "Версия правил платы",
    value: NV_DEFAULTS.feeVersion,
    unit: "",
    source: "DEFAULT_FEE_SETTINGS",
    type: "text",
    readonly: true,
  },
];

/** Settings rows only (without group headings). */
function nvSettingRows() {
  return NV_SETTINGS.filter((r) => r.name);
}

/** Setting by key or by NV_ name. */
function nvSettingDef(keyOrName) {
  return nvSettingRows().find((r) => r.key === keyOrName || r.name === keyOrName) || null;
}

/** Defaults object (the same shape as NV_DEFAULTS) filled from the table: used when the sheet is not built yet. */
function nvDefaultSettings() {
  const s = JSON.parse(JSON.stringify(NV_DEFAULTS));
  nvSettingRows().forEach((r) => {
    if (r.type !== "formula") s[r.key] = r.value;
  });
  s.alerts = [s.alert1 || 6000, s.alert2 || 7000, s.alert3 || 8000, s.alert4 || 9000, s.alert5 || 10000];
  return s;
}
