// The font set of the night design system (docs/design/day-night/DESIGN_SYSTEM.md 2.3). Nothing else is
// allowed: a new face is added here together with a measurement of the font budget (260 KB of woff2).

export type FontRole = "display" | "text" | "condensed" | "mono";
export type LicenseId = "brygada" | "fira-sans" | "fira-condensed" | "plex-mono" | "noto-mono";

export interface FontFace {
  /** Family name as written in `font-family`. */
  readonly family: string;
  readonly weight: 400 | 500 | 600 | 700;
  readonly role: FontRole;
  /** Base of the file name: `<slug>-<weight>.woff2` (site) and `.ttf` (PDF; react-pdf cannot read woff2). */
  readonly slug: string;
  readonly license: LicenseId;
}

/** Only the faces the design uses: Brygada 500 only, Fira Sans 400/500 without italics, Condensed 600/700, mono 400/500. */
export const fontFaces: readonly FontFace[] = [
  { family: "Brygada 1918", weight: 500, role: "display", slug: "brygada-1918", license: "brygada" },
  { family: "Fira Sans", weight: 400, role: "text", slug: "fira-sans", license: "fira-sans" },
  { family: "Fira Sans", weight: 500, role: "text", slug: "fira-sans", license: "fira-sans" },
  {
    family: "Fira Sans Extra Condensed",
    weight: 600,
    role: "condensed",
    slug: "fira-sans-extra-condensed",
    license: "fira-condensed",
  },
  {
    family: "Fira Sans Extra Condensed",
    weight: 700,
    role: "condensed",
    slug: "fira-sans-extra-condensed",
    license: "fira-condensed",
  },
  { family: "IBM Plex Mono", weight: 400, role: "mono", slug: "ibm-plex-mono", license: "plex-mono" },
  { family: "IBM Plex Mono", weight: 500, role: "mono", slug: "ibm-plex-mono", license: "plex-mono" },
  // In IBM Plex Mono the sign U+02BB looks like an acute, so html[lang="uz-Latn"] switches --mono to this family.
  { family: "Noto Sans Mono", weight: 400, role: "mono", slug: "noto-sans-mono", license: "noto-mono" },
  { family: "Noto Sans Mono", weight: 500, role: "mono", slug: "noto-sans-mono", license: "noto-mono" },
];

export function fontFile(face: FontFace, ext: "woff2" | "ttf"): string {
  return `${face.slug}-${face.weight}.${ext}`;
}

export interface FontLicense {
  readonly id: LicenseId;
  /** File in `packages/ui/fonts/licenses/`. */
  readonly file: string;
  /** A string that must be present in the licence text (the copyright holder). */
  readonly copyright: string;
}

export const fontLicenses: readonly FontLicense[] = [
  { id: "brygada", file: "OFL-brygada1918.txt", copyright: "The Brygada 1918 Project Authors" },
  { id: "fira-sans", file: "OFL-firasans.txt", copyright: "The Mozilla Foundation and Telefonica S.A." },
  {
    id: "fira-condensed",
    file: "OFL-firasansextracondensed.txt",
    copyright: "The Mozilla Foundation and Telefonica S.A.",
  },
  { id: "plex-mono", file: "OFL-ibmplexmono.txt", copyright: "IBM Corp." },
  { id: "noto-mono", file: "OFL-notosansmono.txt", copyright: "The Noto Project Authors" },
];

/**
 * Files that predate the design system: apps/web/app/[locale]/layout.tsx still loads them through next/font/local.
 * They go away when that layout switches to the faces above (request to the integrator).
 */
export const legacyFontFiles = ["fira-sans-latin-400-normal.woff2", "fira-sans-latin-600-normal.woff2"] as const;

/**
 * Code points every face must map: Basic Latin, Cyrillic of the Russian text, nbsp, dashes, quotes, minus, numero sign
 * and the two Uzbek modifier letters (oʻ gʻ — U+02BB, other apostrophes — U+02BC).
 */
export const requiredGlyphs: readonly number[] = [
  0x20, 0x30, 0x39, 0x41, 0x5a, 0x61, 0x7a, 0xa0, 0xab, 0xb7, 0xbb, 0x2bb, 0x2bc, 0x401, 0x410, 0x42f, 0x430, 0x44f,
  0x451, 0x2013, 0x2014, 0x2116, 0x2212,
];

/** Text of `styles/fonts.css`: one `@font-face` per face, relative to `src/styles/`. */
export function fontFaceCss(): string {
  const head = "/* Generated by packages/ui/scripts/build-css.mjs from src/fonts/catalog.ts. Do not edit by hand. */\n";
  const rules = fontFaces.map((f) =>
    [
      "@font-face {",
      `  font-family: "${f.family}";`,
      "  font-style: normal;",
      `  font-weight: ${f.weight};`,
      "  font-display: swap;",
      `  src: url("../../fonts/${fontFile(f, "woff2")}") format("woff2");`,
      "}",
    ].join("\n"),
  );
  return `${head}\n${rules.join("\n\n")}\n`;
}
